"""empty message

Revision ID: 862ed783e84d
Revises: 883656b7ff4e
Create Date: 2019-01-02 17:53:00.175637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862ed783e84d'
down_revision = '883656b7ff4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'indicatorvaluecompact',
        sa.Column('timebucket', sa.DateTime(), nullable=False),
        sa.Column('values', sa.Text(), nullable=False),
        sa.Column('indicator_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('timebucket', 'indicator_id', name='indicatorvaluecompact_timebucket_indicator_id_pkey')
    )
    op.create_index(
        op.f('ix_indicatorvaluecompact_indicator_id'), 'indicatorvaluecompact', ['indicator_id'], unique=False)
    op.create_index(
        op.f('ix_indicatorvaluecompact_timebucket'), 'indicatorvaluecompact', ['timebucket'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicatorvaluecompact_timebucket'), table_name='indicatorvaluecompact')
    op.drop_index(op.f('ix_indicatorvaluecompact_indicator_id'), table_name='indicatorvaluecompact')
    op.drop_table('indicatorvaluecompact')
    # ### end Alembic commands ###
